default_agent: FixellaAgent
agents:
  FixellaAgent:
    name: FixellaAgent
    entrypoint: D:/Fixella/backend/agents/mcp_server.py
    platform: linux/arm64
    container_runtime: none
    source_path: D:\Fixella\backend\agents
    aws:
      execution_role: arn:aws:iam::521818209921:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-2829c3f219
      execution_role_auto_create: false
      account: '521818209921'
      region: us-east-2
      ecr_repository: 521818209921.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-fixellaagent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: FixellaAgent-tFe24l5vaJ
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:521818209921:runtime/FixellaAgent-tFe24l5vaJ
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-fixellaagent-builder
      execution_role: arn:aws:iam::521818209921:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-2829c3f219
      source_bucket: bedrock-agentcore-codebuild-sources-521818209921-us-east-2
    memory:
      mode: STM_ONLY
      memory_id: FixellaAgent_mem-Xbc1UL28c8
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:521818209921:memory/FixellaAgent_mem-Xbc1UL28c8
      memory_name: FixellaAgent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
